### ISSUE TITLE
Endless Loop in Updatedb

### ISSUE THREAD

**Issue by antonioG4** [omega8cc/drush#2]
I'm using this version of Drush with Omega's provision, but without the full BOA stack, and things are fine with Drupal 10.1.x sites.  However, when trying to migrate one of those sites to 10.2.x the updatedb command runs endlessly and seems to be looping.  I tracked it down to potentially the wrong batch ID being made available to the underlying Batch process command which then repeatedly calls drush backend updatedb-batch-process with an invalid ID.

Example, Drupal creates a batch ID, 16 for my latest update.  However this code in [batch_10.inc](https://github.com/omega8cc/drush/blob/134a991f72d12a1d724c0fb2c6629f1bc1aeb5be/commands/core/drupal/batch_10.inc#L37) returns ID 44 (which of course continues to change) which is non-existent:

```
// Assign an arbitrary id: don't rely on a serial column in the 'batch'
    // table, since non-progressive batches skip database storage completely.
    $batch['id'] = \Drupal::database()->nextId();
    $args[] = $batch['id'];

    $batch['progressive'] = TRUE;
```

I'll dig on an alternative, but for now I'm putting it out there for others to see and check if they run into the same problem and have a solution.

**Comment by antonioG4** [comment]
See my PR to attempt a fix: https://github.com/omega8cc/drush/pull/3

**Comment by omega8cc** [comment]
We have seen the same happening on some Drupal 10.1 sites, see we will test now if this change helped with batch operations on updatedb/migration. Thanks for the patch!

**Comment by omega8cc** [comment]
It fails with error:

`Missing required argument: batch-id. See `drush help updatedb-batch-process` for information on usage.`

**Comment by omega8cc** [comment]
Here’s a list of relevant issues and attempts to fix the consequences of Drupal API changes in 10.2 affecting batch operations:

https://www.drupal.org/node/3403057

https://www.drupal.org/project/drupal/issues/3337513

https://www.drupal.org/project/drupal/issues/2665216

https://github.com/drush-ops/drush/pull/5809/files/b9bdde6f3e480c86d4e98b7b0651a73c556b407c

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by antonioG4** [comment]
@omega8cc Perhaps this is a better solution.  It seems to mimic what core does and create a batch.  In my cases, a batch exists in the 10.1.7 sites, and when I do my update to 10.2.1 it is available and is picked up by my code.  However, this may create a batch and thus if one doesn't exist in your case it doesn't fail.

https://github.com/drush-ops/drush/pull/5809/files/b9bdde6f3e480c86d4e98b7b0651a73c556b407c

**Comment by omega8cc** [comment]
Yes, it fixed the problem for us and the patch has been applied as hotfix in BOA too. Hopefully this resolves the problem but more testing is welcome.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by antonioG4** [comment]
@omega8cc worked for me. I was able to update from 10.1.7 to 10.2.2 for sites which already had batch IDs and ones without.  Thanks!
