### ISSUE TITLE
BOA Drush 8 with Drupal 10 error:Call to undefined function drupal_required_modules

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/drush#4]
We know this will happen as Drupal 10 needs a different Drush version. However Aegir needs Drush 8.

Using drush pmu xxxx

Error: Call to undefined function drupal_required_modules() in _drush_drupal_required_modules()[error]
(line 50 of /usr/local/share/drush/commands/core/drupal/environment_common.inc) #0
/usr/local/share/drush/includes/environment.inc(803): _drush_drupal_required_modules()
#1 /usr/local/share/drush/commands/core/drupal/pm.inc(26): drush_drupal_required_modules()
#2 /usr/local/share/drush/commands/pm/pm.drush.inc(1265): _drush_pm_uninstall()
#3 /usr/local/share/drush/includes/command.inc(422): drush_pm_uninstall()
#4 /usr/local/share/drush/includes/command.inc(231): _drush_invoke_hooks()
#5 /usr/local/share/drush/includes/command.inc(199): drush_command()
#6 /usr/local/share/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch()
#7 /usr/local/share/drush/includes/preflight.inc(67):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /usr/local/share/drush/drush.php(12): drush_main()
#9 {main}.

It was deprecated in Drupal 9 and subsequently removed:
https://www.drupal.org/project/drupal/issues/3262805#comment-14401112

Here is the patch applied to Drupal core from that issue:
https://git.drupalcode.org/project/drupal/-/commit/e5c38d9

**Comment by omega8cc** [comment]
You should use site local Drush for Drupal 10, but most importantly, you should use Composer and not Drush for codebase management, because Drush already removed support for these features. Please check Drush docs for details.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
https://www.drush.org/12.x/commands/all/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment]
By the way, your Drush path is not a BOA path.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
